// Code generated by protoc-gen-go. DO NOT EDIT.
// source: anything.proto

package examples

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AnythingForYou struct {
	Anything             *any.Any `protobuf:"bytes,1,opt,name=anything,proto3" json:"anything,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AnythingForYou) Reset()         { *m = AnythingForYou{} }
func (m *AnythingForYou) String() string { return proto.CompactTextString(m) }
func (*AnythingForYou) ProtoMessage()    {}
func (*AnythingForYou) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b9e5325d459090b, []int{0}
}

func (m *AnythingForYou) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AnythingForYou.Unmarshal(m, b)
}
func (m *AnythingForYou) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AnythingForYou.Marshal(b, m, deterministic)
}
func (m *AnythingForYou) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnythingForYou.Merge(m, src)
}
func (m *AnythingForYou) XXX_Size() int {
	return xxx_messageInfo_AnythingForYou.Size(m)
}
func (m *AnythingForYou) XXX_DiscardUnknown() {
	xxx_messageInfo_AnythingForYou.DiscardUnknown(m)
}

var xxx_messageInfo_AnythingForYou proto.InternalMessageInfo

func (m *AnythingForYou) GetAnything() *any.Any {
	if m != nil {
		return m.Anything
	}
	return nil
}

func init() {
	proto.RegisterType((*AnythingForYou)(nil), "examples.AnythingForYou")
}

func init() { proto.RegisterFile("anything.proto", fileDescriptor_2b9e5325d459090b) }

var fileDescriptor_2b9e5325d459090b = []byte{
	// 120 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4b, 0xcc, 0xab, 0x2c,
	0xc9, 0xc8, 0xcc, 0x4b, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x48, 0xad, 0x48, 0xcc,
	0x2d, 0xc8, 0x49, 0x2d, 0x96, 0x92, 0x4c, 0xcf, 0xcf, 0x4f, 0xcf, 0x49, 0xd5, 0x07, 0x8b, 0x27,
	0x95, 0xa6, 0xe9, 0x27, 0xe6, 0x55, 0x42, 0x14, 0x29, 0x39, 0x71, 0xf1, 0x39, 0x42, 0xb5, 0xb9,
	0xe5, 0x17, 0x45, 0xe6, 0x97, 0x0a, 0x19, 0x70, 0x71, 0xc0, 0x0c, 0x92, 0x60, 0x54, 0x60, 0xd4,
	0xe0, 0x36, 0x12, 0xd1, 0x83, 0xe8, 0xd7, 0x83, 0xe9, 0xd7, 0x73, 0xcc, 0xab, 0x0c, 0x82, 0xab,
	0x72, 0xe2, 0x8a, 0x82, 0x5b, 0x95, 0xc4, 0x06, 0x56, 0x63, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff,
	0xe7, 0x5e, 0x97, 0x37, 0x8d, 0x00, 0x00, 0x00,
}
