// Code generated by protoc-gen-go. DO NOT EDIT.
// source: exetc.proto

package examples

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 어떻게 converting 되는지 궁금함.
type Foo int32

const (
	Foo_UP Foo = 0
)

var Foo_name = map[int32]string{
	0: "UP",
}

var Foo_value = map[string]int32{
	"UP": 0,
}

func (x Foo) String() string {
	return proto.EnumName(Foo_name, int32(x))
}

func (Foo) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_44bd90b3380b3e53, []int{0}
}

// SearchRespose 메세지에서 Result 라는 메세지를 사용함.
type SearchResponse struct {
	Results              []*Result `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *SearchResponse) Reset()         { *m = SearchResponse{} }
func (m *SearchResponse) String() string { return proto.CompactTextString(m) }
func (*SearchResponse) ProtoMessage()    {}
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_44bd90b3380b3e53, []int{0}
}

func (m *SearchResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchResponse.Unmarshal(m, b)
}
func (m *SearchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchResponse.Marshal(b, m, deterministic)
}
func (m *SearchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchResponse.Merge(m, src)
}
func (m *SearchResponse) XXX_Size() int {
	return xxx_messageInfo_SearchResponse.Size(m)
}
func (m *SearchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SearchResponse proto.InternalMessageInfo

func (m *SearchResponse) GetResults() []*Result {
	if m != nil {
		return m.Results
	}
	return nil
}

type Result struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Snippets             []string `protobuf:"bytes,3,rep,name=snippets,proto3" json:"snippets,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Result) Reset()         { *m = Result{} }
func (m *Result) String() string { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()    {}
func (*Result) Descriptor() ([]byte, []int) {
	return fileDescriptor_44bd90b3380b3e53, []int{1}
}

func (m *Result) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Result.Unmarshal(m, b)
}
func (m *Result) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Result.Marshal(b, m, deterministic)
}
func (m *Result) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Result.Merge(m, src)
}
func (m *Result) XXX_Size() int {
	return xxx_messageInfo_Result.Size(m)
}
func (m *Result) XXX_DiscardUnknown() {
	xxx_messageInfo_Result.DiscardUnknown(m)
}

var xxx_messageInfo_Result proto.InternalMessageInfo

func (m *Result) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Result) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Result) GetSnippets() []string {
	if m != nil {
		return m.Snippets
	}
	return nil
}

// Nest 위의 방식과 다른점 살펴보자.
type SearchResponseNest struct {
	Results              []*SearchResponseNest_ResultNest `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *SearchResponseNest) Reset()         { *m = SearchResponseNest{} }
func (m *SearchResponseNest) String() string { return proto.CompactTextString(m) }
func (*SearchResponseNest) ProtoMessage()    {}
func (*SearchResponseNest) Descriptor() ([]byte, []int) {
	return fileDescriptor_44bd90b3380b3e53, []int{2}
}

func (m *SearchResponseNest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchResponseNest.Unmarshal(m, b)
}
func (m *SearchResponseNest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchResponseNest.Marshal(b, m, deterministic)
}
func (m *SearchResponseNest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchResponseNest.Merge(m, src)
}
func (m *SearchResponseNest) XXX_Size() int {
	return xxx_messageInfo_SearchResponseNest.Size(m)
}
func (m *SearchResponseNest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchResponseNest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchResponseNest proto.InternalMessageInfo

func (m *SearchResponseNest) GetResults() []*SearchResponseNest_ResultNest {
	if m != nil {
		return m.Results
	}
	return nil
}

type SearchResponseNest_ResultNest struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Snippets             []string `protobuf:"bytes,3,rep,name=snippets,proto3" json:"snippets,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchResponseNest_ResultNest) Reset()         { *m = SearchResponseNest_ResultNest{} }
func (m *SearchResponseNest_ResultNest) String() string { return proto.CompactTextString(m) }
func (*SearchResponseNest_ResultNest) ProtoMessage()    {}
func (*SearchResponseNest_ResultNest) Descriptor() ([]byte, []int) {
	return fileDescriptor_44bd90b3380b3e53, []int{2, 0}
}

func (m *SearchResponseNest_ResultNest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchResponseNest_ResultNest.Unmarshal(m, b)
}
func (m *SearchResponseNest_ResultNest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchResponseNest_ResultNest.Marshal(b, m, deterministic)
}
func (m *SearchResponseNest_ResultNest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchResponseNest_ResultNest.Merge(m, src)
}
func (m *SearchResponseNest_ResultNest) XXX_Size() int {
	return xxx_messageInfo_SearchResponseNest_ResultNest.Size(m)
}
func (m *SearchResponseNest_ResultNest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchResponseNest_ResultNest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchResponseNest_ResultNest proto.InternalMessageInfo

func (m *SearchResponseNest_ResultNest) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *SearchResponseNest_ResultNest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *SearchResponseNest_ResultNest) GetSnippets() []string {
	if m != nil {
		return m.Snippets
	}
	return nil
}

type Outer struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Outer) Reset()         { *m = Outer{} }
func (m *Outer) String() string { return proto.CompactTextString(m) }
func (*Outer) ProtoMessage()    {}
func (*Outer) Descriptor() ([]byte, []int) {
	return fileDescriptor_44bd90b3380b3e53, []int{3}
}

func (m *Outer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Outer.Unmarshal(m, b)
}
func (m *Outer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Outer.Marshal(b, m, deterministic)
}
func (m *Outer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Outer.Merge(m, src)
}
func (m *Outer) XXX_Size() int {
	return xxx_messageInfo_Outer.Size(m)
}
func (m *Outer) XXX_DiscardUnknown() {
	xxx_messageInfo_Outer.DiscardUnknown(m)
}

var xxx_messageInfo_Outer proto.InternalMessageInfo

type Outer_MiddleAA struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Outer_MiddleAA) Reset()         { *m = Outer_MiddleAA{} }
func (m *Outer_MiddleAA) String() string { return proto.CompactTextString(m) }
func (*Outer_MiddleAA) ProtoMessage()    {}
func (*Outer_MiddleAA) Descriptor() ([]byte, []int) {
	return fileDescriptor_44bd90b3380b3e53, []int{3, 0}
}

func (m *Outer_MiddleAA) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Outer_MiddleAA.Unmarshal(m, b)
}
func (m *Outer_MiddleAA) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Outer_MiddleAA.Marshal(b, m, deterministic)
}
func (m *Outer_MiddleAA) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Outer_MiddleAA.Merge(m, src)
}
func (m *Outer_MiddleAA) XXX_Size() int {
	return xxx_messageInfo_Outer_MiddleAA.Size(m)
}
func (m *Outer_MiddleAA) XXX_DiscardUnknown() {
	xxx_messageInfo_Outer_MiddleAA.DiscardUnknown(m)
}

var xxx_messageInfo_Outer_MiddleAA proto.InternalMessageInfo

type Outer_MiddleAA_Inner struct {
	Ival                 int64    `protobuf:"varint,1,opt,name=ival,proto3" json:"ival,omitempty"`
	Booly                bool     `protobuf:"varint,2,opt,name=booly,proto3" json:"booly,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Outer_MiddleAA_Inner) Reset()         { *m = Outer_MiddleAA_Inner{} }
func (m *Outer_MiddleAA_Inner) String() string { return proto.CompactTextString(m) }
func (*Outer_MiddleAA_Inner) ProtoMessage()    {}
func (*Outer_MiddleAA_Inner) Descriptor() ([]byte, []int) {
	return fileDescriptor_44bd90b3380b3e53, []int{3, 0, 0}
}

func (m *Outer_MiddleAA_Inner) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Outer_MiddleAA_Inner.Unmarshal(m, b)
}
func (m *Outer_MiddleAA_Inner) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Outer_MiddleAA_Inner.Marshal(b, m, deterministic)
}
func (m *Outer_MiddleAA_Inner) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Outer_MiddleAA_Inner.Merge(m, src)
}
func (m *Outer_MiddleAA_Inner) XXX_Size() int {
	return xxx_messageInfo_Outer_MiddleAA_Inner.Size(m)
}
func (m *Outer_MiddleAA_Inner) XXX_DiscardUnknown() {
	xxx_messageInfo_Outer_MiddleAA_Inner.DiscardUnknown(m)
}

var xxx_messageInfo_Outer_MiddleAA_Inner proto.InternalMessageInfo

func (m *Outer_MiddleAA_Inner) GetIval() int64 {
	if m != nil {
		return m.Ival
	}
	return 0
}

func (m *Outer_MiddleAA_Inner) GetBooly() bool {
	if m != nil {
		return m.Booly
	}
	return false
}

type Outer_MiddleBB struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Outer_MiddleBB) Reset()         { *m = Outer_MiddleBB{} }
func (m *Outer_MiddleBB) String() string { return proto.CompactTextString(m) }
func (*Outer_MiddleBB) ProtoMessage()    {}
func (*Outer_MiddleBB) Descriptor() ([]byte, []int) {
	return fileDescriptor_44bd90b3380b3e53, []int{3, 1}
}

func (m *Outer_MiddleBB) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Outer_MiddleBB.Unmarshal(m, b)
}
func (m *Outer_MiddleBB) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Outer_MiddleBB.Marshal(b, m, deterministic)
}
func (m *Outer_MiddleBB) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Outer_MiddleBB.Merge(m, src)
}
func (m *Outer_MiddleBB) XXX_Size() int {
	return xxx_messageInfo_Outer_MiddleBB.Size(m)
}
func (m *Outer_MiddleBB) XXX_DiscardUnknown() {
	xxx_messageInfo_Outer_MiddleBB.DiscardUnknown(m)
}

var xxx_messageInfo_Outer_MiddleBB proto.InternalMessageInfo

type Outer_MiddleBB_Inner struct {
	Ival                 int32    `protobuf:"varint,1,opt,name=ival,proto3" json:"ival,omitempty"`
	Booly                bool     `protobuf:"varint,2,opt,name=booly,proto3" json:"booly,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Outer_MiddleBB_Inner) Reset()         { *m = Outer_MiddleBB_Inner{} }
func (m *Outer_MiddleBB_Inner) String() string { return proto.CompactTextString(m) }
func (*Outer_MiddleBB_Inner) ProtoMessage()    {}
func (*Outer_MiddleBB_Inner) Descriptor() ([]byte, []int) {
	return fileDescriptor_44bd90b3380b3e53, []int{3, 1, 0}
}

func (m *Outer_MiddleBB_Inner) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Outer_MiddleBB_Inner.Unmarshal(m, b)
}
func (m *Outer_MiddleBB_Inner) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Outer_MiddleBB_Inner.Marshal(b, m, deterministic)
}
func (m *Outer_MiddleBB_Inner) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Outer_MiddleBB_Inner.Merge(m, src)
}
func (m *Outer_MiddleBB_Inner) XXX_Size() int {
	return xxx_messageInfo_Outer_MiddleBB_Inner.Size(m)
}
func (m *Outer_MiddleBB_Inner) XXX_DiscardUnknown() {
	xxx_messageInfo_Outer_MiddleBB_Inner.DiscardUnknown(m)
}

var xxx_messageInfo_Outer_MiddleBB_Inner proto.InternalMessageInfo

func (m *Outer_MiddleBB_Inner) GetIval() int32 {
	if m != nil {
		return m.Ival
	}
	return 0
}

func (m *Outer_MiddleBB_Inner) GetBooly() bool {
	if m != nil {
		return m.Booly
	}
	return false
}

type Person struct {
	// Other fields elided
	Aliases              []string `protobuf:"bytes,8,rep,name=aliases,proto3" json:"aliases,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Person) Reset()         { *m = Person{} }
func (m *Person) String() string { return proto.CompactTextString(m) }
func (*Person) ProtoMessage()    {}
func (*Person) Descriptor() ([]byte, []int) {
	return fileDescriptor_44bd90b3380b3e53, []int{4}
}

func (m *Person) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Person.Unmarshal(m, b)
}
func (m *Person) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Person.Marshal(b, m, deterministic)
}
func (m *Person) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Person.Merge(m, src)
}
func (m *Person) XXX_Size() int {
	return xxx_messageInfo_Person.Size(m)
}
func (m *Person) XXX_DiscardUnknown() {
	xxx_messageInfo_Person.DiscardUnknown(m)
}

var xxx_messageInfo_Person proto.InternalMessageInfo

func (m *Person) GetAliases() []string {
	if m != nil {
		return m.Aliases
	}
	return nil
}

func init() {
	proto.RegisterEnum("examples.Foo", Foo_name, Foo_value)
	proto.RegisterType((*SearchResponse)(nil), "examples.SearchResponse")
	proto.RegisterType((*Result)(nil), "examples.Result")
	proto.RegisterType((*SearchResponseNest)(nil), "examples.SearchResponseNest")
	proto.RegisterType((*SearchResponseNest_ResultNest)(nil), "examples.SearchResponseNest.ResultNest")
	proto.RegisterType((*Outer)(nil), "examples.Outer")
	proto.RegisterType((*Outer_MiddleAA)(nil), "examples.Outer.MiddleAA")
	proto.RegisterType((*Outer_MiddleAA_Inner)(nil), "examples.Outer.MiddleAA.Inner")
	proto.RegisterType((*Outer_MiddleBB)(nil), "examples.Outer.MiddleBB")
	proto.RegisterType((*Outer_MiddleBB_Inner)(nil), "examples.Outer.MiddleBB.Inner")
	proto.RegisterType((*Person)(nil), "examples.Person")
}

func init() { proto.RegisterFile("exetc.proto", fileDescriptor_44bd90b3380b3e53) }

var fileDescriptor_44bd90b3380b3e53 = []byte{
	// 326 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x92, 0xbf, 0x6a, 0xeb, 0x30,
	0x18, 0xc5, 0xaf, 0x2d, 0xdb, 0x51, 0xbe, 0xc0, 0x8d, 0x10, 0x77, 0x30, 0x9e, 0x82, 0x96, 0x6b,
	0x3c, 0x04, 0xee, 0xcd, 0xda, 0x0e, 0xf6, 0x10, 0x28, 0xb4, 0x4d, 0x50, 0xe9, 0xd2, 0xcd, 0x49,
	0x3e, 0xa8, 0x41, 0xb5, 0x8c, 0xa4, 0x94, 0xf4, 0x01, 0xfa, 0x30, 0x7d, 0x4a, 0x97, 0xd8, 0x4d,
	0x42, 0xff, 0xd0, 0xa9, 0xdb, 0x77, 0x8e, 0xce, 0xe1, 0xfc, 0x06, 0xc1, 0x08, 0x77, 0xe8, 0xd6,
	0xd3, 0xc6, 0x68, 0xa7, 0x39, 0xc5, 0x5d, 0xf9, 0xd0, 0x28, 0xb4, 0xe2, 0x0c, 0x7e, 0xdf, 0x60,
	0x69, 0xd6, 0xf7, 0x12, 0x6d, 0xa3, 0x6b, 0x8b, 0x3c, 0x83, 0x81, 0x41, 0xbb, 0x55, 0xce, 0xc6,
	0xde, 0x84, 0xa4, 0xa3, 0xff, 0x6c, 0x7a, 0x48, 0x4f, 0x65, 0xf7, 0x20, 0x0f, 0x01, 0x71, 0x09,
	0x51, 0x6f, 0x71, 0x06, 0x64, 0x6b, 0x54, 0xec, 0x4d, 0xbc, 0x74, 0x28, 0xf7, 0x27, 0xff, 0x03,
	0xa1, 0xab, 0x9c, 0xc2, 0xd8, 0xef, 0xbc, 0x5e, 0xf0, 0x04, 0xa8, 0xad, 0xab, 0xa6, 0x41, 0x67,
	0x63, 0x32, 0x21, 0xe9, 0x50, 0x1e, 0xb5, 0x78, 0xf1, 0x80, 0xbf, 0x87, 0xb9, 0x46, 0xeb, 0x78,
	0xfe, 0x11, 0xe8, 0xef, 0x09, 0xe8, 0x73, 0xfc, 0x8d, 0x71, 0x7f, 0x1e, 0x39, 0x93, 0x25, 0xc0,
	0xc9, 0xfe, 0x11, 0xd6, 0x67, 0x0f, 0xc2, 0xc5, 0xd6, 0xa1, 0x49, 0xce, 0x81, 0x5e, 0x55, 0x9b,
	0x8d, 0xc2, 0x3c, 0x4f, 0xfe, 0x41, 0x78, 0x51, 0xd7, 0x68, 0x38, 0x87, 0xa0, 0x7a, 0x2c, 0xfb,
	0x0d, 0x22, 0xbb, 0x7b, 0x3f, 0xb2, 0xd2, 0x5a, 0x3d, 0x75, 0x23, 0x54, 0xf6, 0xe2, 0x54, 0x2f,
	0x8a, 0xaf, 0xeb, 0xe1, 0x77, 0x75, 0x21, 0x20, 0x5a, 0xa2, 0xb1, 0xba, 0xe6, 0x31, 0x0c, 0x4a,
	0x55, 0x95, 0x16, 0x6d, 0x4c, 0x3b, 0xd8, 0x83, 0xcc, 0x66, 0x40, 0xe6, 0x5a, 0xf3, 0x08, 0xfc,
	0xdb, 0x25, 0xfb, 0x25, 0x02, 0xea, 0x33, 0x5f, 0x04, 0x74, 0xcc, 0xc6, 0x22, 0xa0, 0x43, 0x36,
	0x12, 0x94, 0xa6, 0xac, 0x6d, 0xdb, 0x76, 0x90, 0x91, 0xf9, 0x62, 0x91, 0x91, 0x22, 0x97, 0x05,
	0xdc, 0x1d, 0x3f, 0xc9, 0x2a, 0xea, 0x7e, 0xcd, 0xec, 0x35, 0x00, 0x00, 0xff, 0xff, 0x7a, 0x36,
	0xb1, 0xa1, 0x44, 0x02, 0x00, 0x00,
}
