// Code generated by protoc-gen-go. DO NOT EDIT.
// source: exoneof.proto

package examples

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Patch struct {
	// 이름을 잘 지어주어야 한다.
	//
	// Types that are valid to be assigned to Op:
	//	*Patch_CopyOp
	//	*Patch_InsertOp
	Op                   isPatch_Op `protobuf_oneof:"op"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Patch) Reset()         { *m = Patch{} }
func (m *Patch) String() string { return proto.CompactTextString(m) }
func (*Patch) ProtoMessage()    {}
func (*Patch) Descriptor() ([]byte, []int) {
	return fileDescriptor_68e1b51676f190f5, []int{0}
}

func (m *Patch) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Patch.Unmarshal(m, b)
}
func (m *Patch) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Patch.Marshal(b, m, deterministic)
}
func (m *Patch) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Patch.Merge(m, src)
}
func (m *Patch) XXX_Size() int {
	return xxx_messageInfo_Patch.Size(m)
}
func (m *Patch) XXX_DiscardUnknown() {
	xxx_messageInfo_Patch.DiscardUnknown(m)
}

var xxx_messageInfo_Patch proto.InternalMessageInfo

type isPatch_Op interface {
	isPatch_Op()
}

type Patch_CopyOp struct {
	CopyOp *Patch_Copy `protobuf:"bytes,3,opt,name=copy_op,json=copyOp,proto3,oneof"`
}

type Patch_InsertOp struct {
	InsertOp *Patch_Insert `protobuf:"bytes,4,opt,name=insert_op,json=insertOp,proto3,oneof"`
}

func (*Patch_CopyOp) isPatch_Op() {}

func (*Patch_InsertOp) isPatch_Op() {}

func (m *Patch) GetOp() isPatch_Op {
	if m != nil {
		return m.Op
	}
	return nil
}

func (m *Patch) GetCopyOp() *Patch_Copy {
	if x, ok := m.GetOp().(*Patch_CopyOp); ok {
		return x.CopyOp
	}
	return nil
}

func (m *Patch) GetInsertOp() *Patch_Insert {
	if x, ok := m.GetOp().(*Patch_InsertOp); ok {
		return x.InsertOp
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Patch) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Patch_CopyOp)(nil),
		(*Patch_InsertOp)(nil),
	}
}

type Patch_Copy struct {
	Start                int64    `protobuf:"varint,1,opt,name=start,proto3" json:"start,omitempty"`
	End                  int64    `protobuf:"varint,2,opt,name=end,proto3" json:"end,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Patch_Copy) Reset()         { *m = Patch_Copy{} }
func (m *Patch_Copy) String() string { return proto.CompactTextString(m) }
func (*Patch_Copy) ProtoMessage()    {}
func (*Patch_Copy) Descriptor() ([]byte, []int) {
	return fileDescriptor_68e1b51676f190f5, []int{0, 0}
}

func (m *Patch_Copy) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Patch_Copy.Unmarshal(m, b)
}
func (m *Patch_Copy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Patch_Copy.Marshal(b, m, deterministic)
}
func (m *Patch_Copy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Patch_Copy.Merge(m, src)
}
func (m *Patch_Copy) XXX_Size() int {
	return xxx_messageInfo_Patch_Copy.Size(m)
}
func (m *Patch_Copy) XXX_DiscardUnknown() {
	xxx_messageInfo_Patch_Copy.DiscardUnknown(m)
}

var xxx_messageInfo_Patch_Copy proto.InternalMessageInfo

func (m *Patch_Copy) GetStart() int64 {
	if m != nil {
		return m.Start
	}
	return 0
}

func (m *Patch_Copy) GetEnd() int64 {
	if m != nil {
		return m.End
	}
	return 0
}

type Patch_Insert struct {
	RawBytes             []byte   `protobuf:"bytes,1,opt,name=raw_bytes,json=rawBytes,proto3" json:"raw_bytes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Patch_Insert) Reset()         { *m = Patch_Insert{} }
func (m *Patch_Insert) String() string { return proto.CompactTextString(m) }
func (*Patch_Insert) ProtoMessage()    {}
func (*Patch_Insert) Descriptor() ([]byte, []int) {
	return fileDescriptor_68e1b51676f190f5, []int{0, 1}
}

func (m *Patch_Insert) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Patch_Insert.Unmarshal(m, b)
}
func (m *Patch_Insert) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Patch_Insert.Marshal(b, m, deterministic)
}
func (m *Patch_Insert) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Patch_Insert.Merge(m, src)
}
func (m *Patch_Insert) XXX_Size() int {
	return xxx_messageInfo_Patch_Insert.Size(m)
}
func (m *Patch_Insert) XXX_DiscardUnknown() {
	xxx_messageInfo_Patch_Insert.DiscardUnknown(m)
}

var xxx_messageInfo_Patch_Insert proto.InternalMessageInfo

func (m *Patch_Insert) GetRawBytes() []byte {
	if m != nil {
		return m.RawBytes
	}
	return nil
}

type Instructions struct {
	Operations           []*Patch `protobuf:"bytes,1,rep,name=operations,proto3" json:"operations,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Instructions) Reset()         { *m = Instructions{} }
func (m *Instructions) String() string { return proto.CompactTextString(m) }
func (*Instructions) ProtoMessage()    {}
func (*Instructions) Descriptor() ([]byte, []int) {
	return fileDescriptor_68e1b51676f190f5, []int{1}
}

func (m *Instructions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Instructions.Unmarshal(m, b)
}
func (m *Instructions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Instructions.Marshal(b, m, deterministic)
}
func (m *Instructions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Instructions.Merge(m, src)
}
func (m *Instructions) XXX_Size() int {
	return xxx_messageInfo_Instructions.Size(m)
}
func (m *Instructions) XXX_DiscardUnknown() {
	xxx_messageInfo_Instructions.DiscardUnknown(m)
}

var xxx_messageInfo_Instructions proto.InternalMessageInfo

func (m *Instructions) GetOperations() []*Patch {
	if m != nil {
		return m.Operations
	}
	return nil
}

func init() {
	proto.RegisterType((*Patch)(nil), "examples.Patch")
	proto.RegisterType((*Patch_Copy)(nil), "examples.Patch.Copy")
	proto.RegisterType((*Patch_Insert)(nil), "examples.Patch.Insert")
	proto.RegisterType((*Instructions)(nil), "examples.Instructions")
}

func init() { proto.RegisterFile("exoneof.proto", fileDescriptor_68e1b51676f190f5) }

var fileDescriptor_68e1b51676f190f5 = []byte{
	// 243 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0x41, 0x4b, 0x03, 0x31,
	0x10, 0x85, 0x9b, 0xee, 0x76, 0xdd, 0x4e, 0x2b, 0x4a, 0x28, 0x12, 0xea, 0x65, 0x29, 0x08, 0x7b,
	0x4a, 0xa1, 0xe2, 0x59, 0x58, 0x2f, 0xed, 0xa9, 0x92, 0xa3, 0x97, 0x92, 0xae, 0x11, 0x0b, 0x9a,
	0x19, 0x92, 0x48, 0xbb, 0xff, 0xd1, 0x1f, 0x25, 0xc9, 0xa2, 0x48, 0x6f, 0x79, 0xe1, 0xfb, 0x1e,
	0xc3, 0x83, 0x4b, 0x73, 0x42, 0x6b, 0xf0, 0x4d, 0x92, 0xc3, 0x80, 0xbc, 0x34, 0x27, 0xfd, 0x49,
	0x1f, 0xc6, 0x2f, 0xbe, 0x19, 0x8c, 0x9e, 0x75, 0x68, 0xdf, 0xf9, 0x12, 0x2e, 0x5a, 0xa4, 0x6e,
	0x87, 0x24, 0xb2, 0x8a, 0xd5, 0x93, 0xd5, 0x4c, 0xfe, 0x52, 0x32, 0x11, 0xf2, 0x09, 0xa9, 0x5b,
	0x0f, 0x54, 0x11, 0xb1, 0x2d, 0xf1, 0x07, 0x18, 0x1f, 0xac, 0x37, 0x2e, 0x44, 0x25, 0x4f, 0xca,
	0xcd, 0xb9, 0xb2, 0x49, 0xc0, 0x7a, 0xa0, 0xca, 0x1e, 0xdd, 0xd2, 0x5c, 0x42, 0x1e, 0x8b, 0xf8,
	0x0c, 0x46, 0x3e, 0x68, 0x17, 0x04, 0xab, 0x58, 0x9d, 0xa9, 0x3e, 0xf0, 0x6b, 0xc8, 0x8c, 0x7d,
	0x15, 0xc3, 0xf4, 0x17, 0x9f, 0xf3, 0x3b, 0x28, 0xfa, 0x16, 0x7e, 0x0b, 0x63, 0xa7, 0x8f, 0xbb,
	0x7d, 0x17, 0x8c, 0x4f, 0xd6, 0x54, 0x95, 0x4e, 0x1f, 0x9b, 0x98, 0x9b, 0x1c, 0x86, 0x48, 0x8b,
	0x47, 0x98, 0x6e, 0xac, 0x0f, 0xee, 0xab, 0x0d, 0x07, 0xb4, 0x9e, 0x2f, 0x01, 0x90, 0x8c, 0xd3,
	0x29, 0x09, 0x56, 0x65, 0xf5, 0x64, 0x75, 0x75, 0x76, 0xa4, 0xfa, 0x87, 0x34, 0xf0, 0xf2, 0xb7,
	0xcd, 0xbe, 0x48, 0x63, 0xdd, 0xff, 0x04, 0x00, 0x00, 0xff, 0xff, 0x5c, 0x7f, 0xb7, 0xc3, 0x3d,
	0x01, 0x00, 0x00,
}
