// Code generated by protoc-gen-go. DO NOT EDIT.
// source: jobs.proto

package greet

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	_struct "github.com/golang/protobuf/ptypes/struct"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type JobsResponse_Status int32

const (
	JobsResponse_IN_PROGRESS JobsResponse_Status = 0
	JobsResponse_CANCELED    JobsResponse_Status = 1
	JobsResponse_FAILED      JobsResponse_Status = 2
	JobsResponse_COMPLETED   JobsResponse_Status = 3
	JobsResponse_TIME_OUT    JobsResponse_Status = 4
	JobsResponse_FINISHED    JobsResponse_Status = 5
)

var JobsResponse_Status_name = map[int32]string{
	0: "IN_PROGRESS",
	1: "CANCELED",
	2: "FAILED",
	3: "COMPLETED",
	4: "TIME_OUT",
	5: "FINISHED",
}

var JobsResponse_Status_value = map[string]int32{
	"IN_PROGRESS": 0,
	"CANCELED":    1,
	"FAILED":      2,
	"COMPLETED":   3,
	"TIME_OUT":    4,
	"FINISHED":    5,
}

func (x JobsResponse_Status) String() string {
	return proto.EnumName(JobsResponse_Status_name, int32(x))
}

func (JobsResponse_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_45644d4410f878a7, []int{1, 0}
}

type JobsRequest struct {
	JobReqId             int64                     `protobuf:"varint,1,opt,name=job_req_id,json=jobReqId,proto3" json:"job_req_id,omitempty"`
	InputData            map[string]*_struct.Value `protobuf:"bytes,2,rep,name=input_data,json=inputData,proto3" json:"input_data,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	InputMessage         *any.Any                  `protobuf:"bytes,3,opt,name=input_message,json=inputMessage,proto3" json:"input_message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *JobsRequest) Reset()         { *m = JobsRequest{} }
func (m *JobsRequest) String() string { return proto.CompactTextString(m) }
func (*JobsRequest) ProtoMessage()    {}
func (*JobsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_45644d4410f878a7, []int{0}
}

func (m *JobsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobsRequest.Unmarshal(m, b)
}
func (m *JobsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobsRequest.Marshal(b, m, deterministic)
}
func (m *JobsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobsRequest.Merge(m, src)
}
func (m *JobsRequest) XXX_Size() int {
	return xxx_messageInfo_JobsRequest.Size(m)
}
func (m *JobsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_JobsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_JobsRequest proto.InternalMessageInfo

func (m *JobsRequest) GetJobReqId() int64 {
	if m != nil {
		return m.JobReqId
	}
	return 0
}

func (m *JobsRequest) GetInputData() map[string]*_struct.Value {
	if m != nil {
		return m.InputData
	}
	return nil
}

func (m *JobsRequest) GetInputMessage() *any.Any {
	if m != nil {
		return m.InputMessage
	}
	return nil
}

type JobsResponse struct {
	JobReqId             int64                     `protobuf:"varint,1,opt,name=job_req_id,json=jobReqId,proto3" json:"job_req_id,omitempty"`
	Status               JobsResponse_Status       `protobuf:"varint,2,opt,name=status,proto3,enum=jobs.JobsResponse_Status" json:"status,omitempty"`
	OutputData           map[string]*_struct.Value `protobuf:"bytes,3,rep,name=output_data,json=outputData,proto3" json:"output_data,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	OutputMessage        *any.Any                  `protobuf:"bytes,4,opt,name=output_message,json=outputMessage,proto3" json:"output_message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *JobsResponse) Reset()         { *m = JobsResponse{} }
func (m *JobsResponse) String() string { return proto.CompactTextString(m) }
func (*JobsResponse) ProtoMessage()    {}
func (*JobsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_45644d4410f878a7, []int{1}
}

func (m *JobsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobsResponse.Unmarshal(m, b)
}
func (m *JobsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobsResponse.Marshal(b, m, deterministic)
}
func (m *JobsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobsResponse.Merge(m, src)
}
func (m *JobsResponse) XXX_Size() int {
	return xxx_messageInfo_JobsResponse.Size(m)
}
func (m *JobsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_JobsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_JobsResponse proto.InternalMessageInfo

func (m *JobsResponse) GetJobReqId() int64 {
	if m != nil {
		return m.JobReqId
	}
	return 0
}

func (m *JobsResponse) GetStatus() JobsResponse_Status {
	if m != nil {
		return m.Status
	}
	return JobsResponse_IN_PROGRESS
}

func (m *JobsResponse) GetOutputData() map[string]*_struct.Value {
	if m != nil {
		return m.OutputData
	}
	return nil
}

func (m *JobsResponse) GetOutputMessage() *any.Any {
	if m != nil {
		return m.OutputMessage
	}
	return nil
}

func init() {
	proto.RegisterEnum("jobs.JobsResponse_Status", JobsResponse_Status_name, JobsResponse_Status_value)
	proto.RegisterType((*JobsRequest)(nil), "jobs.JobsRequest")
	proto.RegisterMapType((map[string]*_struct.Value)(nil), "jobs.JobsRequest.InputDataEntry")
	proto.RegisterType((*JobsResponse)(nil), "jobs.JobsResponse")
	proto.RegisterMapType((map[string]*_struct.Value)(nil), "jobs.JobsResponse.OutputDataEntry")
}

func init() { proto.RegisterFile("jobs.proto", fileDescriptor_45644d4410f878a7) }

var fileDescriptor_45644d4410f878a7 = []byte{
	// 497 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x93, 0x4d, 0x6f, 0xd3, 0x4c,
	0x14, 0x85, 0xeb, 0x38, 0x8d, 0x9a, 0xeb, 0x24, 0xf5, 0x3b, 0x7a, 0x85, 0xd2, 0xa8, 0x8b, 0x28,
	0xab, 0x2c, 0xa8, 0x0d, 0x41, 0xaa, 0xf8, 0x58, 0xa0, 0x90, 0xb8, 0xe0, 0x2a, 0x1f, 0xd5, 0x24,
	0x61, 0xc1, 0x82, 0x68, 0x1c, 0x0f, 0xae, 0x8b, 0xeb, 0x49, 0x3c, 0x33, 0x95, 0xbc, 0xe5, 0x57,
	0xf0, 0x67, 0x91, 0x90, 0x67, 0x9a, 0x52, 0x1a, 0x04, 0x42, 0x62, 0x77, 0xef, 0xdc, 0xe7, 0x1e,
	0x9f, 0x39, 0xf2, 0x00, 0x5c, 0xb1, 0x80, 0x3b, 0xeb, 0x8c, 0x09, 0x86, 0xca, 0x45, 0xdd, 0x3a,
	0x8e, 0x18, 0x8b, 0x12, 0xea, 0xaa, 0xb3, 0x40, 0x7e, 0x72, 0xb9, 0xc8, 0xe4, 0x4a, 0x68, 0xa6,
	0x75, 0xf4, 0x70, 0x4a, 0xd2, 0x5c, 0x8f, 0x3a, 0xdf, 0x0c, 0xb0, 0xce, 0x59, 0xc0, 0x31, 0xdd,
	0x48, 0xca, 0x05, 0x3a, 0x56, 0xe2, 0xcb, 0x8c, 0x6e, 0x96, 0x71, 0xd8, 0x34, 0xda, 0x46, 0xd7,
	0xc4, 0x07, 0x57, 0x2c, 0xc0, 0x74, 0xe3, 0x87, 0xe8, 0x35, 0x40, 0x9c, 0xae, 0xa5, 0x58, 0x86,
	0x44, 0x90, 0x66, 0xa9, 0x6d, 0x76, 0xad, 0x5e, 0xdb, 0x51, 0x6e, 0xee, 0x89, 0x38, 0x7e, 0xc1,
	0x0c, 0x89, 0x20, 0x5e, 0x2a, 0xb2, 0x1c, 0x57, 0xe3, 0x6d, 0x8f, 0x5e, 0x40, 0x5d, 0x0b, 0x5c,
	0x53, 0xce, 0x49, 0x44, 0x9b, 0x66, 0xdb, 0xe8, 0x5a, 0xbd, 0xff, 0x1d, 0xed, 0xd0, 0xd9, 0x3a,
	0x74, 0xfa, 0x69, 0x8e, 0x6b, 0x0a, 0x1d, 0x6b, 0xb2, 0x35, 0x87, 0xc6, 0xcf, 0xba, 0xc8, 0x06,
	0xf3, 0x33, 0xcd, 0x95, 0xc9, 0x2a, 0x2e, 0x4a, 0xf4, 0x18, 0xf6, 0x6f, 0x48, 0x22, 0x69, 0xb3,
	0xa4, 0x64, 0x1f, 0xed, 0xc8, 0xbe, 0x2f, 0xa6, 0x58, 0x43, 0x2f, 0x4b, 0xcf, 0x8d, 0xce, 0x57,
	0x13, 0x6a, 0xda, 0x3a, 0x5f, 0xb3, 0x94, 0xd3, 0x3f, 0x04, 0xf0, 0x14, 0x2a, 0x5c, 0x10, 0x21,
	0xb9, 0xfa, 0x42, 0xa3, 0x77, 0x74, 0xff, 0xf2, 0x5a, 0xc1, 0x99, 0x29, 0x00, 0xdf, 0x82, 0x68,
	0x00, 0x16, 0x93, 0xe2, 0x2e, 0x34, 0x53, 0x85, 0xd6, 0xf9, 0xc5, 0xde, 0x54, 0x51, 0x3f, 0x62,
	0x03, 0x76, 0x77, 0x80, 0x5e, 0x41, 0xe3, 0x56, 0x64, 0x1b, 0x5c, 0xf9, 0x37, 0xc1, 0xd5, 0x35,
	0xbb, 0x4d, 0x6e, 0x01, 0x87, 0x0f, 0xb4, 0xff, 0x49, 0x74, 0x1f, 0xa1, 0xa2, 0xaf, 0x8a, 0x0e,
	0xc1, 0xf2, 0x27, 0xcb, 0x0b, 0x3c, 0x7d, 0x8b, 0xbd, 0xd9, 0xcc, 0xde, 0x43, 0x35, 0x38, 0x18,
	0xf4, 0x27, 0x03, 0x6f, 0xe4, 0x0d, 0x6d, 0x03, 0x01, 0x54, 0xce, 0xfa, 0x7e, 0x51, 0x97, 0x50,
	0x1d, 0xaa, 0x83, 0xe9, 0xf8, 0x62, 0xe4, 0xcd, 0xbd, 0xa1, 0x6d, 0x16, 0xe0, 0xdc, 0x1f, 0x7b,
	0xcb, 0xe9, 0x62, 0x6e, 0x97, 0x8b, 0xee, 0xcc, 0x9f, 0xf8, 0xb3, 0x77, 0xde, 0xd0, 0xde, 0xef,
	0x7d, 0x31, 0xc0, 0x1e, 0xb1, 0x34, 0x1a, 0xc5, 0x37, 0x34, 0x3c, 0x67, 0xc1, 0x80, 0x24, 0x09,
	0x3a, 0x85, 0xea, 0x4c, 0x06, 0x7c, 0x95, 0xc5, 0x01, 0x45, 0xff, 0xed, 0xfc, 0x7a, 0x2d, 0xb4,
	0x1b, 0x6c, 0x67, 0xef, 0x89, 0x81, 0x4e, 0xc1, 0x5a, 0xa4, 0xfc, 0xaf, 0x37, 0xdf, 0xb8, 0x1f,
	0x4e, 0xa2, 0x58, 0x5c, 0xca, 0xc0, 0x59, 0xb1, 0x6b, 0x97, 0x53, 0x96, 0x5f, 0x12, 0x1a, 0xa7,
	0x6e, 0xc4, 0x12, 0x92, 0x46, 0x27, 0x5c, 0xc8, 0x30, 0xd7, 0xef, 0x8a, 0xbb, 0xc5, 0x7e, 0x50,
	0x51, 0xcd, 0xb3, 0xef, 0x01, 0x00, 0x00, 0xff, 0xff, 0x84, 0x81, 0xa0, 0x19, 0xa4, 0x03, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// LongLivedJobCallClient is the client API for LongLivedJobCall service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LongLivedJobCallClient interface {
	Subscribe(ctx context.Context, in *JobsRequest, opts ...grpc.CallOption) (LongLivedJobCall_SubscribeClient, error)
	Unsubscribe(ctx context.Context, in *JobsRequest, opts ...grpc.CallOption) (*JobsResponse, error)
}

type longLivedJobCallClient struct {
	cc *grpc.ClientConn
}

func NewLongLivedJobCallClient(cc *grpc.ClientConn) LongLivedJobCallClient {
	return &longLivedJobCallClient{cc}
}

func (c *longLivedJobCallClient) Subscribe(ctx context.Context, in *JobsRequest, opts ...grpc.CallOption) (LongLivedJobCall_SubscribeClient, error) {
	stream, err := c.cc.NewStream(ctx, &_LongLivedJobCall_serviceDesc.Streams[0], "/jobs.LongLivedJobCall/Subscribe", opts...)
	if err != nil {
		return nil, err
	}
	x := &longLivedJobCallSubscribeClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type LongLivedJobCall_SubscribeClient interface {
	Recv() (*JobsResponse, error)
	grpc.ClientStream
}

type longLivedJobCallSubscribeClient struct {
	grpc.ClientStream
}

func (x *longLivedJobCallSubscribeClient) Recv() (*JobsResponse, error) {
	m := new(JobsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *longLivedJobCallClient) Unsubscribe(ctx context.Context, in *JobsRequest, opts ...grpc.CallOption) (*JobsResponse, error) {
	out := new(JobsResponse)
	err := c.cc.Invoke(ctx, "/jobs.LongLivedJobCall/Unsubscribe", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LongLivedJobCallServer is the server API for LongLivedJobCall service.
type LongLivedJobCallServer interface {
	Subscribe(*JobsRequest, LongLivedJobCall_SubscribeServer) error
	Unsubscribe(context.Context, *JobsRequest) (*JobsResponse, error)
}

// UnimplementedLongLivedJobCallServer can be embedded to have forward compatible implementations.
type UnimplementedLongLivedJobCallServer struct {
}

func (*UnimplementedLongLivedJobCallServer) Subscribe(req *JobsRequest, srv LongLivedJobCall_SubscribeServer) error {
	return status.Errorf(codes.Unimplemented, "method Subscribe not implemented")
}
func (*UnimplementedLongLivedJobCallServer) Unsubscribe(ctx context.Context, req *JobsRequest) (*JobsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Unsubscribe not implemented")
}

func RegisterLongLivedJobCallServer(s *grpc.Server, srv LongLivedJobCallServer) {
	s.RegisterService(&_LongLivedJobCall_serviceDesc, srv)
}

func _LongLivedJobCall_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(JobsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LongLivedJobCallServer).Subscribe(m, &longLivedJobCallSubscribeServer{stream})
}

type LongLivedJobCall_SubscribeServer interface {
	Send(*JobsResponse) error
	grpc.ServerStream
}

type longLivedJobCallSubscribeServer struct {
	grpc.ServerStream
}

func (x *longLivedJobCallSubscribeServer) Send(m *JobsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _LongLivedJobCall_Unsubscribe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JobsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LongLivedJobCallServer).Unsubscribe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/jobs.LongLivedJobCall/Unsubscribe",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LongLivedJobCallServer).Unsubscribe(ctx, req.(*JobsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _LongLivedJobCall_serviceDesc = grpc.ServiceDesc{
	ServiceName: "jobs.LongLivedJobCall",
	HandlerType: (*LongLivedJobCallServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Unsubscribe",
			Handler:    _LongLivedJobCall_Unsubscribe_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Subscribe",
			Handler:       _LongLivedJobCall_Subscribe_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "jobs.proto",
}
