// Code generated by protoc-gen-go. DO NOT EDIT.
// source: exmap.proto

package examples

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Name struct {
	Names2               map[int64]string `protobuf:"bytes,1,rep,name=names2,proto3" json:"names2,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Name) Reset()         { *m = Name{} }
func (m *Name) String() string { return proto.CompactTextString(m) }
func (*Name) ProtoMessage()    {}
func (*Name) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0d8fb07d4fce02d, []int{0}
}

func (m *Name) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Name.Unmarshal(m, b)
}
func (m *Name) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Name.Marshal(b, m, deterministic)
}
func (m *Name) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Name.Merge(m, src)
}
func (m *Name) XXX_Size() int {
	return xxx_messageInfo_Name.Size(m)
}
func (m *Name) XXX_DiscardUnknown() {
	xxx_messageInfo_Name.DiscardUnknown(m)
}

var xxx_messageInfo_Name proto.InternalMessageInfo

func (m *Name) GetNames2() map[int64]string {
	if m != nil {
		return m.Names2
	}
	return nil
}

func init() {
	proto.RegisterType((*Name)(nil), "grpc_examples.Name")
	proto.RegisterMapType((map[int64]string)(nil), "grpc_examples.Name.Names2Entry")
}

func init() { proto.RegisterFile("exmap.proto", fileDescriptor_d0d8fb07d4fce02d) }

var fileDescriptor_d0d8fb07d4fce02d = []byte{
	// 145 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4e, 0xad, 0xc8, 0x4d,
	0x2c, 0xd0, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x48, 0xad, 0x48, 0xcc, 0x2d, 0xc8, 0x49,
	0x2d, 0x56, 0x2a, 0xe5, 0x62, 0xf1, 0x4b, 0xcc, 0x4d, 0x15, 0x32, 0xe2, 0x62, 0xcb, 0x4b, 0xcc,
	0x4d, 0x2d, 0x36, 0x92, 0x60, 0x54, 0x60, 0xd6, 0xe0, 0x36, 0x92, 0xd2, 0x83, 0x29, 0xd1, 0x03,
	0xc9, 0x83, 0x89, 0x62, 0x23, 0xd7, 0xbc, 0x92, 0xa2, 0xca, 0x20, 0xa8, 0x4a, 0x29, 0x4b, 0x2e,
	0x6e, 0x24, 0x61, 0x21, 0x01, 0x2e, 0xe6, 0xec, 0xd4, 0x4a, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xe6,
	0x20, 0x10, 0x53, 0x48, 0x84, 0x8b, 0xb5, 0x2c, 0x31, 0xa7, 0x34, 0x55, 0x82, 0x49, 0x81, 0x51,
	0x83, 0x33, 0x08, 0xc2, 0xb1, 0x62, 0xb2, 0x60, 0x74, 0xe2, 0x8a, 0x82, 0x3b, 0x21, 0x89, 0x0d,
	0xec, 0x26, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0xe0, 0x24, 0x8c, 0xd4, 0xa2, 0x00, 0x00,
	0x00,
}
